; PlatformIO Project Configuration File for libFRX
; A modular shared library for FRX ecosystem devices

; ============================================================================
; Base Configuration
; ============================================================================
[_env]
platform = espressif32
framework = arduino
extra_scripts = pre:shared/scripts/get_time.py
platform_packages =
    platformio/toolchain-xtensa@^2.100300.220621
    tool-esptoolpy@~1.40501.0
lib_deps =
    jescore@2.3.1
build_flags =
    -Ilib/audio
    -Ilib/dsp_frx
    -Ilib/ext_flash
    -Ilib/i2c
    -Ilib/sdcard
    -Ilib/synth
    -Ilib/syserr
    -Ilib/utils
    -Ilib/wav
    -DJES_LOG_LEN=16
    -DFRX_FW_VER_MAJ=0
    -DFRX_FW_VER_MIN=1
    -DFRX_FW_VER_MOD=97 ; 'a'
    -DFR1_SER_NUM=0

; ============================================================================
; FRX Configuration (concrete testing setup at jesdev.io)
; ============================================================================
[env:frx_base]
extends = _env
board = esp32-s3-devkitc-1
upload_speed = 921600
monitor_speed = 115200
build_flags =
    ${_env.build_flags}
    ; generic things
    -DUTILS_DEBUG_PRINT_ENABLE
    ; Audio pins
    -DAUDIO_I2S_PORT=0
    -DAUDIO_PIN_MEMS_I2S_BCLK=15
    -DAUDIO_PIN_MEMS_I2S_WS=17
    -DAUDIO_PIN_MEMS_I2S_IN=16
    -DAUDIO_PIN_DAC_I2S_OUT=6
    ; I2C pins
    -DI2C_BASE_SCL=21
    -DI2C_BASE_SDA=20
    -DI2C_BASE_NUM=0
    ; External Flash pins
    -DEF_SPI_HOST=1
    -DEF_PIN_MISO=46
    -DEF_PIN_MOSI=11
    -DEF_PIN_SCLK=12
    -DEF_PIN_CS=14
    ; SDCard (SDMMC mode)
    -DSDCARD_MODE_SDMMC
    -DSDCARD_SDMMC_PIN_CLK=36
    -DSDCARD_SDMMC_PIN_CMD=35
    -DSDCARD_SDMMC_PIN_D0=37
    -DSDCARD_SDMMC_PIN_D1=38
    -DSDCARD_SDMMC_PIN_D2=45
    -DSDCARD_SDMMC_PIN_D3=39
    '-DSDCARD_DEFAULT_FNAME_WAV="fr2_rec_0000.wav"'
    ; Existing modules on setup at jesdev.io
    -DFRX_ENABLE_MODULE_SYSERR
    -DFRX_ENABLE_MODULE_AUDIO
    -DFRX_ENABLE_MODULE_DSP_FRX
    -DFRX_ENABLE_MODULE_EXT_FLASH
    -DFRX_ENABLE_MODULE_I2C
    -DFRX_ENABLE_MODULE_SDCARD
    -DFRX_ENABLE_MODULE_SYNTH
    -DFRX_ENABLE_MODULE_UTILS
    -DFRX_ENABLE_MODULE_WAV

[env:frx_test_audio]
extends = env:frx_base
test_filter = test_audio

[env:frx_test_dsp_frx]
extends = env:frx_base
test_filter = test_dsp_frx

[env:frx_test_ext_flash]
extends = env:frx_base
test_filter = test_ext_flash

[env:frx_test_i2c]
extends = env:frx_base
test_filter = test_i2c

[env:frx_test_sdcard]
extends = env:frx_base
test_filter = test_sdcard

[env:fr1_test_sdcard_spi]
; NOTE:
; This env will eventually be migrated to the
; ESP32-S3 env above. This requires a physical
; test-setup that has both an SDMMC and SPI
; connection to two independent SD cards.
extends = _env
board = esp-wrover-kit
upload_speed = 921600
monitor_speed = 115200
build_flags =
    ${_env.build_flags}
    -DUTILS_DEBUG_PRINT_ENABLE
    ; FR1-mini SD card SPI configuration
    -DSDCARD_MODE_SPI
    -DSDCARD_SPI_PIN_CS=13
    -DSDCARD_SPI_PIN_MOSI=15
    -DSDCARD_SPI_PIN_MISO=2
    -DSDCARD_SPI_PIN_SCK=14
    -DSDCARD_MAX_FREQ_BUS_DEFAULT=SDMMC_FREQ_52M
    '-DSDCARD_DEFAULT_FNAME_WAV="fr2_rec_0000.wav"'
    -DFRX_ENABLE_MODULE_SYSERR
    -DFRX_ENABLE_MODULE_SDCARD
    -DFRX_ENABLE_MODULE_UTILS
test_filter = test_sdcard

[env:frx_test_synth]
extends = env:frx_base
test_filter = test_synth
build_flags =
    ${env:frx_base.build_flags}
    -O3
    -ffast-math

[env:frx_test_utils]
extends = env:frx_base
test_filter = test_utils

[env:frx_test_wav]
extends = env:frx_base
test_filter = test_wav

