# Auto-generated from audio_jccl.h
# Do not edit manually!

AUDIO_SERVER_JOB_NAME = r"audiosrv"
AUDIO_CONTROL_JOB_NAME = r"audioctrl"
AUDIO_CMD_RESTART = r"restart"
AUDIO_CMD_STOP = r"stop"
AUDIO_CMD_VOLUME = r"vol"
AUDIO_CMD_MUTE = r"mute"
AUDIO_CMD_STATUS = r"status"
AUDIO_OPT_SR = r"sr"
AUDIO_OPT_SR_DASH = r"\-sr"
AUDIO_OPT_BPS = r"bps"
AUDIO_OPT_BPS_DASH = r"\-bps"
AUDIO_OPT_GAIN = r"gain"
AUDIO_OPT_GAIN_DASH = r"\-gain"
AUDIO_CMDS = r"Commands: "
AUDIO_MSG_UNKNOWN_CMD = r"Unknown audio command\."
AUDIO_MSG_OFFLINE = r"Audio already offline\."
AUDIO_MSG_ERROR_USAGE = r"Audio command usage error\."
AUDIO_MSG_ERROR_ERRNUM = r"Audio command failed with error \d+\."
AUDIO_MSG_RESTARTED = r"Audio restarted\."
AUDIO_MSG_STOPPED = r"Audio stopped\."
AUDIO_MSG_VOLUME = r"Audio volume set to \d+/1000\."
AUDIO_MSG_STATUS = r"Audio status: running=%u sr=%lu bps=%u gain=\d+/1000 nch=%u banks=%u\."
