# Auto-generated from sdcard_jccl.h
# Do not edit manually!

SDCARD_JOB_NAME = r"sdcard"
SDCARD_STREAMER_JOB_NAME = r"sdstrm"
SDCARD_CMD_MOUNT = r"mnt"
SDCARD_CMD_UNMOUNT = r"unmnt"
SDCARD_CMD_HELP = r"help"
SDCARD_CMD_LIST = r"ls"
SDCARD_CMD_READ = r"cat"
SDCARD_CMD_CREATE = r"mk"
SDCARD_CMD_REMOVE = r"rm"
SDCARD_CMD_MEMORY = r"mem"
SDCARD_CMDS = r"Available commands: "
SDCARD_MSG_MOUNTED = r"Mounted\."
SDCARD_MSG_MOUNT_FAIL = r"Unable to mount SD card!"
SDCARD_MSG_UNMOUNTED = r"Unmounted\."
SDCARD_MSG_UNMOUNT_FAIL = r"Unable to unmount SD card!"
SDCARD_MSG_LS_ERROR_errnum = r"Error while listing files\. \(\d+\)"
SDCARD_MSG_CAT_ERROR_USAGE = r"Specify a file to read\."
SDCARD_MSG_CAT_ERROR_errnum = r"Error while reading file\. \(\d+\)"
SDCARD_MSG_MK_ERROR_errnum = r"Error while creating file\. \(\d+\)"
SDCARD_MSG_MK_ERROR_USAGE = r"Specify a file to create\."
SDCARD_MSG_RM_ERROR_errnum = r"Error while deleting file\. \(\d+\)"
SDCARD_MSG_RM_ERROR_USAGE = r"Specify a file to delete\."
SDCARD_MSG_MEM_FORMAT_free_tot = r"\d+/\d+ kB free"
SDCARD_MSG_MEM_ERROR_errnum = r"Free space can't be identified\. \(\d+\)"
SDCARD_MSG_UNKNOWN_CMD = r"Unknown SD command\."
